name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (ffmpeg)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Generate demo (1 participant, 3s)
        run: python tools/simulate.py --participants 1 --out ./DSP_Sim --duration 3

      - name: Convert to MP3 (best-effort)
        run: python tools/export_mp3.py --root ./DSP_Sim --bitrate 160k || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DSP_Sim
          path: DSP_Sim
